'use strict';

/**
 * Built-in card formats available to the Access Database UI.
 *
 * Source:
 *   - Schlage Credential Formats-200624.pdf
 *   - User-provided card format JSON
 */
module.exports = [
  {
    value: 'H10301',
    label: 'H10301 - 26 bits standard',
    fc: { min: 0, max: 255 },
    payload: {
      offset: 0,
      total_card_bits: 26,
      format: 'WIEGAND',
      total_even_parity_bits: 13,
      even_parity_start_bit: 0,
      total_odd_parity_bits: 13,
      odd_parity_start_bit: 13,
      total_facility_code_bits: 8,
      facility_code_start_bit: 1,
      total_cardholder_id_bits: 16,
      cardholder_id_start_bit: 9,
      card_format_code: 'H10301',
      is_parity_calculation_by_2_bits: false,
      is_corporate_card: false,
      is_37_bit_parity_test_with_4_bits: false,
      is_37_bit_parity_test_with_2_bits: false,
      is_48_bit_card_formatting: false,
      is_special_card_format: false,
      is_reverse_card_format: false,
      is_large_encoded_id: false,
      is_reversal_of_bytes: false,
      is_37_bit_special_parity_test: false,
      is_200_bit_fascn_to_128_bit_version_conversation: false,
      is_card_id_check_with_other_formats: false,
      enable_corporate_1000_parity_checks: false,
      total_issue_code_bits: 0,
      issue_code_start_bit: 0,
      min_number_of_digits: 0,
      max_number_of_digits: 0,
    },
  },
  {
    value: 'H10302',
    label: 'H10302 - 37 bits without FC',
    fc: null,
    payload: {
      offset: 0,
      total_card_bits: 37,
      format: 'WIEGAND',
      facility_code: -1,
      total_even_parity_bits: 19,
      even_parity_start_bit: 0,
      total_odd_parity_bits: 19,
      odd_parity_start_bit: 18,
      total_facility_code_bits: 0,
      facility_code_start_bit: 0,
      total_cardholder_id_bits: 35,
      cardholder_id_start_bit: 1,
      card_format_code: 'H10302',
      is_parity_calculation_by_2_bits: false,
      is_corporate_card: false,
      is_37_bit_parity_test_with_4_bits: false,
      is_37_bit_parity_test_with_2_bits: false,
      is_48_bit_card_formatting: false,
      is_special_card_format: false,
      is_reverse_card_format: false,
      is_large_encoded_id: false,
      is_reversal_of_bytes: false,
      is_37_bit_special_parity_test: false,
      is_200_bit_fascn_to_128_bit_version_conversation: false,
      is_card_id_check_with_other_formats: false,
      enable_corporate_1000_parity_checks: false,
      total_issue_code_bits: 0,
      issue_code_start_bit: 0,
      min_number_of_digits: 0,
      max_number_of_digits: 0,
    },
  },
  {
    value: 'H10304',
    label: 'H10304 - 37 bits with FC',
    fc: { min: 0, max: 65535 },
    payload: {
      offset: 0,
      total_card_bits: 37,
      format: 'WIEGAND',
      total_even_parity_bits: 19,
      even_parity_start_bit: 0,
      total_odd_parity_bits: 19,
      odd_parity_start_bit: 18,
      total_facility_code_bits: 16,
      facility_code_start_bit: 1,
      total_cardholder_id_bits: 19,
      cardholder_id_start_bit: 17,
      card_format_code: 'H10304',
      is_parity_calculation_by_2_bits: false,
      is_corporate_card: false,
      is_37_bit_parity_test_with_4_bits: false,
      is_37_bit_parity_test_with_2_bits: false,
      is_48_bit_card_formatting: false,
      is_special_card_format: false,
      is_reverse_card_format: false,
      is_large_encoded_id: false,
      is_reversal_of_bytes: false,
      is_37_bit_special_parity_test: false,
      is_200_bit_fascn_to_128_bit_version_conversation: false,
      is_card_id_check_with_other_formats: false,
      enable_corporate_1000_parity_checks: false,
      total_issue_code_bits: 0,
      issue_code_start_bit: 0,
      min_number_of_digits: 0,
      max_number_of_digits: 0,
    },
  },
  {
    value: 'H5XXXX',
    label: 'HID Corporate 1000 - 35 Format',
    fc: null,
    payload: {
      total_card_bits: 35,
      format: 'WIEGAND',
      offset: 0,
      total_even_parity_bits: 0,
      even_parity_start_bit: 0,
      total_odd_parity_bits: 0,
      odd_parity_start_bit: 0,
      total_facility_code_bits: 12,
      facility_code_start_bit: 2,
      total_cardholder_id_bits: 20,
      cardholder_id_start_bit: 14,
      card_format_code: 'H5XXXX',
      is_parity_calculation_by_2_bits: false,
      is_corporate_card: false,
      is_37_bit_parity_test_with_4_bits: false,
      is_37_bit_parity_test_with_2_bits: false,
      is_48_bit_card_formatting: false,
      is_special_card_format: false,
      is_reverse_card_format: false,
      is_large_encoded_id: false,
      is_reversal_of_bytes: false,
      is_37_bit_special_parity_test: false,
      is_200_bit_fascn_to_128_bit_version_conversation: false,
      is_card_id_check_with_other_formats: false,
      enable_corporate_1000_parity_checks: true,
      total_issue_code_bits: 0,
      issue_code_start_bit: 0,
      min_number_of_digits: 0,
      max_number_of_digits: 0,
    },
  },
  {
    value: 'H2XXXX',
    label: 'HID Corporate 1000 - 48 Format',
    fc: null,
    payload: {
      total_card_bits: 48,
      format: 'WIEGAND',
      offset: 0,
      total_even_parity_bits: 0,
      even_parity_start_bit: 0,
      total_odd_parity_bits: 0,
      odd_parity_start_bit: 0,
      total_facility_code_bits: 22,
      facility_code_start_bit: 2,
      total_cardholder_id_bits: 23,
      cardholder_id_start_bit: 24,
      card_format_code: 'H2XXXX',
      is_parity_calculation_by_2_bits: false,
      is_corporate_card: false,
      is_37_bit_parity_test_with_4_bits: false,
      is_37_bit_parity_test_with_2_bits: false,
      is_48_bit_card_formatting: false,
      is_special_card_format: false,
      is_reverse_card_format: false,
      is_large_encoded_id: false,
      is_reversal_of_bytes: false,
      is_37_bit_special_parity_test: false,
      is_200_bit_fascn_to_128_bit_version_conversation: false,
      is_card_id_check_with_other_formats: false,
      enable_corporate_1000_parity_checks: true,
      total_issue_code_bits: 0,
      issue_code_start_bit: 0,
      min_number_of_digits: 0,
      max_number_of_digits: 0,
    },
  },
];
